### PR TITLE
Custom template functions

### PR DESCRIPTION
**Pull request by jamesholcomb**
This is a first shot at supporting parameterless template functions for scenarios where supplying data from faker is not practical or possible.

I initially attempted to swap out faker.js for casual.js to support custom generators.  I **reverted** the change since I had problems getting them to work inside mustache templates.

Also in this PR, I swapped out console debugging for `debug` logging.

### CODE REVIEW

**Comment by thosakwe** [comment]
Thanks!

**Comment by jamesholcomb** [comment]
Is it ready to publish to npm?

**Comment by thosakwe** [comment]
Yep, I'll do it tomorrow morning (or later tonight).

**Comment by jamesholcomb** [comment]
Any updates?

I would link to my git url fork but since this repo does not track `lib`, it makes it cumbersome to automate the build...for more on that => https://github.com/npm/npm/issues/3055#issuecomment-196750271

**Comment by thosakwe** [comment]
Yeah, will push right about now. Also gonna modify the .gitignore to track `lib`

**Comment by thosakwe** [comment]
@jamesholcomb Done

**Pull request merged**
