### PR TITLE
Add support for feathers v3

### PR DESCRIPTION
**Pull request by josx**
I need to use this with the newer feathers version 3.x
I have done the changes to support it.

### CODE REVIEW

**Comment by thosakwe** [comment]
Seems like the tests are failing on Node 5. Can you check that out? Thanks

**Comment by josx** [comment]
So ,sorry about that, but i found out that feather v3 requires node >= 6.
Check it on [package.json](https://github.com/feathersjs/feathers/blob/master/package.json)

**Comment by thosakwe** [comment]
Hm, in that case, the version of `feathers-seeder` will need to be bumped `2.0.0` to represent a breaking change.

In addition, the `.travis.yml` configuration will need to be modified to only run on Node 6 and up.

**Comment by thosakwe** [comment]
Thanks for the contribution! Going to get this published in a few minutes.

**Comment by josx** [comment]
Done!
Replace node 5 with node 8, and bump to 2.0.0

**Comment by josx** [comment]
great! thanks!

**Comment by thosakwe** [comment]
Now published: https://www.npmjs.com/package/feathers-seeder/v/2.0.0

**Comment by afifsohaili** [comment]
thanks guys!

**Pull request merged**
